apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lens-user
  namespace: monitoring
roleRef:
  kind: Role
  name: lens-user
  apiGroup: rbac.authorization.k8s.io
subjects:
  # Note that you can specify more than one "subject"
  - kind: Group
    name: example-group@elastisys.com
    apiGroup: rbac.authorization.k8s.io
  - kind: User
    name: some.person@elastisys.com
    apiGroup: rbac.authorization.k8s.io
