apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
  namespace: kafka
spec:
  containers:
  - image: quay.io/strimzi/kafka:0.38.0-kafka-3.6.0
    name: kafka-producer
    resources:
      requests:
        memory: 128Mi
        cpu: 200m
      limits:
        memory: 256Mi
        cpu: 400m
    command: ["sleep"]
    args: ["5000"]
  restartPolicy: Never
