default: true

MD003: # heading-style
  style: atx
MD004: # ul-style
  style: dash
MD007: # ul-indent
  indent: 4
MD009: # no-trailing-spaces
  strict: true
MD010: # no-hard-tabs
  spaces_per_tab: 4
MD013: false # line-length - does not support editorconfig
MD024: # no-duplicate-heading
  siblings_only: true
MD026: # no-trailing-punctuation
  punctuation: .,:;
MD029: # ol-prefix
  style: one
MD033: # no-inline-html
  allowed_elements:
    - a
    - br
    - dd
    - details
    - div
    - dl
    - dt
    - embed
    - figure
    - figcaption
    - img
    - li
    - nav
    - section
    - strong
    - summary
    - sup
    - ul
MD034: false # no-bare-urls
MD044: # proper-names
  code_blocks: false
  html_elements: false
  names:
    - Alertmanager
    - AMS
    - Ansible
    - ArgoCD
    - AWS
    - Azure
    - cert-manager
    - Cleura
    - Cluster API
    - Welkin Apps
    - compliantkubernetes-apps
    - compliantkubernetes-kubespray
    - compliantkubernetes-postgresql
    - compliantkubernetes-rabbitmq
    - compliantkubernetes-redis
    - ConfigMap
    - DaemonSet
    - Dex
    - Elastisys
    - "!!! elastisys"
    - Elastx
    - Exoscale
    - Falco
    - Fluentd
    - GitHub
    - Grafana
    - Harbor
    - Ingress
    - Ingress Controller
    - Jaeger
    - jaeger-operator
    - Kubernetes
    - Kubernetes Service
    - Kubernetes Secrets
    - Kubespray
    - kube-prometheus-stack
    - LoadBalancer
    - Network Policy
    - Network Policies
    - NetworkPolicy
    - NetworkPolicies
    - NGINX
    - NodePort
    - OpenSearch
    - OpenSearch Dashboards
    - Pod
    - Pod Security Policy
    - Pod Security Policies
    - Pod Security Standard
    - Pod Security Standards
    - PostgreSQL
    - postgres-operator
    - Prometheus
    - prometheus-operator
    - RabbitMQ
    - rabbitmq-operator
    - Redis
    - redis-operator
    - Service type ClusterIP
    - Service type LoadBalancer
    - Service type NodePort
    - ReplicaSet
    - Safespring
    - S3
    - StatefulSet
    - Thanos
MD046: false # code-block-style - does not support admonitions
MD048: false # code-fence-style - does not support admonitions
MD049: # emphasis-style
  style: underscore
MD050: # strong-style
  style: asterisk
