apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.6.0
    replicas: 1
    resources:
      requests:
        memory: 384Mi
        cpu: 50m
      limits:
        memory: 384Mi
        cpu: 200m
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 15
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 15
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: true
  zookeeper:
    replicas: 1
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 15
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 15
    resources:
      requests:
        memory: 384Mi
        cpu: 50m
      limits:
        memory: 384Mi
        cpu: 200m
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  entityOperator:
    tlsSidecar:
      readinessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 15
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 15
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 150m
          memory: 128Mi
    topicOperator:
      readinessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 15
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 15
      resources:
        requests:
          memory: 384Mi
          cpu: 100m
        limits:
          memory: 384Mi
          cpu: 150m
    userOperator:
      readinessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 15
      livenessProbe:
        initialDelaySeconds: 60
        timeoutSeconds: 15
      resources:
        requests:
          memory: 384Mi
          cpu: 100m
        limits:
          memory: 384Mi
          cpu: 150m
