{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "welkin-user-demo.fullname" . }}
  labels:
    {{- include "welkin-user-demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "welkin-user-demo.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
{{- end }}
