apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lens-user
  namespace: monitoring
roleRef:
  kind: Role
  name: lens-user
  apiGroup: rbac.authorization.k8s.io
subjects:
# Note that you can specify more than one "subject"
- kind: User
  name: lars.larsson@elastisys.com
  apiGroup: rbac.authorization.k8s.io
