apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: monitoring
  name: lens-user
rules:
- apiGroups:
  - ""
  resources:
  - pods/portforward
  - pods/proxy
  - services/portforward
  - services/proxy
  verbs:
  - get
  - list
  - create
  - delete
