name: Regularly check links

on:
  schedule:
    # Runs "At 08:30 on every day-of-week from Monday through Friday." (see https://crontab.guru)
    - cron: '30 8 * * 1-5'

jobs:
  build:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Install linkchecker
        run: apt install linkchecker
      - name: Run linkchecker
        run: linkchecker https://elastisys.io
