name: Regularly check links

on:
  schedule:
    # Runs "At 08:30 on every day-of-week from Monday through Friday." (see https://crontab.guru)
    - cron: '40 8 * * 1-5'

jobs:
  build:
    name: Check links
    runs-on: ubuntu-latest
    steps:
      - name: Install linkchecker
        run: sudo apt install linkchecker
      - name: Run linkchecker
        run: |
          export OPENSSL_CONF=openssl.cnf
          linkchecker \
            --no-robots \
            --check-extern \
            --ignore-url '\/\/localhost' \
            --ignore-url '\/\/127.0.0.1' \
            https://elastisys.io
