name: lint

on:
  pull_request:
    branches:
      - 'main'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
      - name: Test docs
        run: |
          python3 -m pip install -r ./requirements.txt
          mkdocs build
      - name: Check for stranded HTML tags in the rendered HTML which indicate broken Markdown code
        run: |
          FILES=$(find site -name '*.html' -print)
          echo "Checking $(echo $FILES | wc -w) files ..."
          ! egrep '&lt;(br|img)' $FILES
