name: lint

on:
  pull_request:
    branches:
      - 'main'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
      - name: Test docs
        run: |
          python3 -m pip install -r ./requirements.txt
          mkdocs build
