name: lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install Node dependencies
        run: npm ci

      - name: Install Python requirements
        run: python3 -m pip install -r ./requirements.txt

      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch

      - name: Auto-generate documentation
        run: ./scripts/jsonschema2md.sh
        env:
          OVERRIDE_REF_NAME: main

      - name: Build docs
        run: mkdocs build

      - name: Check for stranded HTML tags in the rendered HTML which indicate broken Markdown code
        run: |
          FILES=$(find site -name '*.html' -print)
          echo "Checking $(echo $FILES | wc -w) files ..."
          ! egrep '&lt;(br|div|img|p>)' $FILES
